In [1]:
import numpy as np
from scipy import linalg

In [2]:
def linsolve(A,b):
    x = linalg.solve(A, b)
    return x

In [3]:
def sigma(seq):
    if seq == 'AB':
        sig=+1
    elif seq == 'BA':
        sig=-1
    elif seq == 'BC':
        sig=+1
    elif seq == 'CB':
        sig=-1
    elif seq == 'CA':
        sig=+1
    elif seq == 'AC':
        sig=-1
    return sig

In [4]:
def Supercell(stack):
    
    N_supercell=20
    
    Layers=[]
    for j in range(0,N_supercell):
        for i in range(len(stack)):
            Layers.append(stack[i]) 
            
    return Layers

# Stoichiometric matrix with pairwise terms

In [5]:
def stoiJ(stack,N_int):
    stacks=Supercell(stack)
    A=[]
    for i in range(len(stack)):
        sig_i=sigma(stacks[i]+stacks[i+1])
        row=[]
        for j in range(1,N_int+1):
            sig_j=sigma(stacks[i+j]+stacks[i+j+1])
            row.append(-sig_i*sig_j)
        A.append(row)
    A=np.array(A)/len(stack)
    row=[1]
    for j in range(0,N_int):
        row.append(np.sum(A[:,j]))
    return row

In [6]:
def StoiMatJ(stacks,N_int):
    
    A=[]
    
    for stack in stacks:
        row=stoiJ(stack,N_int)
        A.append(row)
        
    A=np.array(A)
    return A

In [7]:
stacks=['AB','ABC','ABAC','ABABC','ABABAC','ABACBC']
A=StoiMatJ(stacks,3)  # interactions until the third later
print(A)

[[ 1.          1.         -1.          1.        ]
 [ 1.         -1.         -1.         -1.        ]
 [ 1.          0.          1.          0.        ]
 [ 1.         -0.2        -0.2        -0.2       ]
 [ 1.          0.33333333  0.33333333 -0.33333333]
 [ 1.         -0.33333333  0.33333333  1.        ]]


# Stoichiometric matrix with pairwise terms and a 4-body term

In [8]:
def stoiJK(stack,N_int):
    
    stacks=Supercell(stack)
    
    A=[]
    for i in range(len(stack)):
        sig_i=sigma(stacks[i]+stacks[i+1])
        row=[]
        for j in range(1,N_int+1):
            sig_j=sigma(stacks[i+j]+stacks[i+j+1])
            #row.append(-sig_i*sig_j)
            row.append(sig_i*sig_j)
        sig_i1=sigma(stacks[i+1]+stacks[i+2])
        sig_i2=sigma(stacks[i+2]+stacks[i+3])
        sig_i3=sigma(stacks[i+3]+stacks[i+4])
        #row.append(-sig_i*sig_i1*sig_i2*sig_i3)
        row.append(sig_i*sig_i1*sig_i2*sig_i3)
        A.append(row)
        
    A=np.array(A)/len(stack)

    row=[1]
    for j in range(0,N_int+1):
        row.append(np.sum(A[:,j]))
        
    return row

In [9]:
def StoiMatJK(stacks,N_int):
    
    A=[]
    
    for stack in stacks:
        row=stoiJK(stack,N_int)
        A.append(row)
        
    A=np.array(A)
    
    return A

In [10]:
stacks=['AB','ABC','ABAC','ABABC','ABABAC','ABACBC']
A=StoiMatJK(stacks,3) # interactions until the third later
print(A)

[[ 1.         -1.          1.         -1.          1.        ]
 [ 1.          1.          1.          1.          1.        ]
 [ 1.          0.         -1.          0.          1.        ]
 [ 1.          0.2         0.2         0.2        -0.6       ]
 [ 1.         -0.33333333 -0.33333333  0.33333333  0.33333333]
 [ 1.          0.33333333 -0.33333333 -1.         -0.33333333]]
